addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.19")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"          % "0.5.1")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"         % "0.9.19")
addSbtPlugin("com.typesafe.sbt"         %% "sbt-native-packager"  % "1.7.4")
